parameters:
#    wapistrano_profile.example.class: Wapistrano\ProfileBundle\Example

services:
    wapistrano_profile.password_encoder:
        class: Wapistrano\ProfileBundle\Security\WapistranoPasswordEncoder

    wapistrano_profile.action_listener:
        class: Wapistrano\ProfileBundle\Listener\UserRightsListener
        arguments: [ @wapistrano_profile.user_rights ]
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }

    wapistrano_profile.user_rights:
        class: Wapistrano\ProfileBundle\Security\WapistranoUserRights
        arguments: [ @security.context, @doctrine.orm.entity_manager ]
