wapistrano_profile:
    resource: "@WapistranoProfileBundle/Controller"
    prefix:   /
    type: annotation

wapistrano_core:
    resource: "@WapistranoCoreBundle/Controller"
    prefix:   /
    type: annotation

