security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Wapistrano\CoreBundle\Entity\Users:
            id: wapistrano_profile.password_encoder

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        wapistrano:
            name: wapistrano_security_provider
            entity:
                class: WapistranoCoreBundle:Users



    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/login$
            security: false

        secured_area:
            pattern:    ^/
            form_login:
                check_path: login_check
                login_path: wapistrano_profile_security_login
            logout:
                path:   logout
                target: wapistrano_profile_security_login
            provider: wapistrano_security_provider
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/hosts, roles: ROLE_ADMIN }
        - { path: ^/recipes, roles: ROLE_ADMIN }
        - { path: ^/users/$, roles: ROLE_ADMIN }
