services:
    wapistrano_core.twig.menu_extension:
        class: Wapistrano\CoreBundle\Twig\MenuExtension
        arguments: [ @service_container ]
        tags:
            - { name: twig.extension }

    wapistrano_core.twig.configuration_extension:
        class: Wapistrano\CoreBundle\Twig\ConfigurationExtension
        arguments: [ @service_container ]
        tags:
            - { name: twig.extension }

    wapistrano_core.twig.stage_extension:
        class: Wapistrano\CoreBundle\Twig\StageExtension
        arguments: [ @service_container ]
        tags:
            - { name: twig.extension }

    wapistrano_core.twig.role_extension:
        class: Wapistrano\CoreBundle\Twig\RoleExtension
        arguments: [ @service_container ]
        tags:
            - { name: twig.extension }

    wapistrano_core.twig.deployment_extension:
            class: Wapistrano\CoreBundle\Twig\DeploymentExtension
            arguments: [ @service_container ]
            tags:
                - { name: twig.extension }

    wapistrano_core.twig.misc_extension:
        class: Wapistrano\CoreBundle\Twig\MiscExtension
        arguments: [ @service_container ]
        tags:
            - { name: twig.extension }

    wapistrano_core.menu:
        class: Wapistrano\CoreBundle\Menu\Menu
        arguments: [ @doctrine.orm.entity_manager, @wapistrano_profile.user_rights ]

    wapistrano_core.configuration:
        class: Wapistrano\CoreBundle\Configuration\Configuration
        arguments: [ @request_stack, @doctrine.orm.entity_manager, @form.factory, @twig, @router, @wapistrano_core.stage ]

    wapistrano_core.stage:
        class: Wapistrano\CoreBundle\Stage\Stage
        arguments: [ @request_stack, @doctrine.orm.entity_manager, @form.factory, @twig, @router, @wapistrano_core.gearman, @logger ]

    wapistrano_core.role:
        class: Wapistrano\CoreBundle\Role\Role
        arguments: [ @request_stack, @doctrine.orm.entity_manager, @form.factory, @twig, @router, @wapistrano_core.stage ]

    wapistrano_core.user:
        class: Wapistrano\CoreBundle\User\User
        arguments: [ @request_stack, @doctrine.orm.entity_manager, @form.factory, @twig, @router, @security.context ]

    wapistrano_core.gearman:
        class:  Wapistrano\CoreBundle\Broker\Gearman
        arguments: [ %wapistrano_core%, @logger ]