services:
    wapistrano_core.twig.menu_extension:
        class: Wapistrano\CoreBundle\Twig\MenuExtension
        arguments: [ @service_container ]
        tags:
            - { name: twig.extension }

    wapistrano_core.twig.configuration_extension:
            class: Wapistrano\CoreBundle\Twig\ConfigurationExtension
            arguments: [ @service_container ]
            tags:
                - { name: twig.extension }
    wapistrano_core.menu:
        class: Wapistrano\CoreBundle\Menu\Menu
        arguments: [ @doctrine.orm.entity_manager ]

    wapistrano_core.configuration:
        class: Wapistrano\CoreBundle\Configuration\Configuration
        arguments: [ @request_stack, @doctrine.orm.entity_manager, @form.factory, @twig ]