parameters:
    wapistrano_carrier.transit_dir: %kernel.root_dir%/../src/Wapistrano/CarrierBundle/Resources/importExport/
    wapistrano_carrier.serialiser.subscriber.class: Wapistrano\CarrierBundle\Subscriber\JmsSubscriber

services:
    wapistrano_carrier.serialiser.subscriber:
        class: %wapistrano_carrier.serialiser.subscriber.class%
        calls:
            - [ setEm, [ @doctrine.orm.entity_manager ] ]
        tags:
            - { name: jms_serializer.event_subscriber }
