parameters:
    wapistrano_carrier.transit_dir: %kernel.root_dir%/../src/Wapistrano/CarrierBundle/Resources/importExport/

services:
#    wapistrano_carrier.example:
#        class: %wapistrano_carrier.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
