parameters:
#    wapistrano_carrier.example.class: Wapistrano\CarrierBundle\Example

services:
#    wapistrano_carrier.example:
#        class: %wapistrano_carrier.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
