parameters:
#    wapistrano_core.example.class: Wapistrano\CoreBundle\Example

services:
#    wapistrano_core.example:
#        class: %wapistrano_core.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
